#server port
server:
    port:8040
#connection mongodb
spring:
    data:
        mongodb:
            uri:mongodb://localhost:27017/bank
client:
    service:
        url:http://localhost:8030/api/client/
movement:
    service:
        url:http://localhost:8050/api/movement/