#server port
server:
    port:8050
#connection mongodb
spring:
    data:
        mongodb:
            uri=mongodb://localhost:27017/bank
debit:
    service:
        url:http://localhost:8040/api/debit/

credit:
    service:
        url:http://localhost:8020/api/credit/