#server port
server:
    port: 8010

#connection mongodb
spring:
    appllication:
        name: bank-service-card
    data:
        mongodb:
            uri: mongodb://localhost:27017/bank
    config:
        import: optional:configserver:http://localhost:8888